version: '3.7'

services:
  stump_backend:
    build:
      context: ./stump_backend
      dockerfile: Dockerfile.prod
    command: gunicorn stump_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - stump_prod_api_static_content:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./stump_backend/.env.prod
    depends_on:
      - postgres

  postgres:
    image: postgres:10.12-alpine
    volumes:
      - stump_prod_postgres:/var/lib/postgresql/data
    env_file:
      - ./stump_backend/.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - stump_prod_api_static_content:/home/app/web/staticfiles
    ports:
      - 8080:80
    depends_on:
      - stump_backend

volumes:
  stump_prod_postgres:
  stump_prod_api_static_content:
