version: '3.7'

services:
  api:
    build:
      context: ./stump_backend/
      dockerfile: Dockerfile.local
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./stump_backend:/usr/src/stump_backend
    ports:
      - "8000:8000"
    env_file:
      - ./stump_backend/.env.dev
  postgres:
    image: postgres:10.12-alpine
    volumes:
      - stump_dev_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=stump_dev
      - POSTGRES_PASSWORD=stump_dev
      - POSTGRES_DB=stump_dev

volumes:
  stump_dev_postgres:
