version: '3.7'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    command: gunicorn stump_backend.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./api/.env.prod
    depends_on:
      - postgres

  postgres:
    image: postgres:10.12-alpine
    volumes:
      - stump_prod_postgres:/var/lib/postgresql/data
    env_file:
      - ./api/.env.prod.db

  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - api

volumes:
  stump_prod_postgres:
